bash "$(pwd)/.object/rxfetch"

alias c="clear"
alias ls="lsd"
alias la="lsd -a"
alias rm="rm -rf"
alias mkdir="mkdir -p"
alias .="cd .."
alias ..="cd ../.."
alias ...="cd ../../../"
alias ....="cd ../../../../"
alias pins="apt install -y"
alias puns="apt remove -y"

function temp {
	clear
	mkdir "$1" && cd "$1"
	mkdir -p "src/js" "src/css"
	touch "index.html" "src/js/main.js" "src/css/style.css"
	local text=$1
	echo '<!DOCTYPE html>
<html lang="en">
<head>

	<!-- Console For Development -->
	<script src="//cdn.jsdelivr.net/npm/eruda"></script>
	<script>eruda.init();</script>

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="./src/css/style.css"/>
	<title>'$text'</title>
</head>
<body>
	<h1>'$text'</h1>
	<script src="./src/js/main.js" type="module"></script>
</body>
</html>' >> index.html

	echo '* {
	padding: 0;
	margin: 0;
}

body {
	width: 100%;
	height: 100vh;
	background: #383a3f;
	color: white;
}' >> "src/css/style.css"

	echo 'console.log("Hello, World")' >> "src/js/main.js"
	
	live-server
}

function run {
  local apk_name="$1"
  case "$apk_name" in
    "bstation")
      package_name="com.bstar.intl"
      launcher_activity="tv.danmaku.bili.ui.splash.SplashActivity"
      ;;
    "acode")
      package_name="com.foxdebug.acode"
      launcher_activity="com.foxdebug.acode.MainActivity"
      ;;
    "wa")
      package_name="com.whatsapp"
      launcher_activity="com.whatsapp.Main"
      ;;
    "drive")
      package_name="com.google.android.apps.docs"
      launcher_activity="com.google.android.apps.docs.app.NewMainProxyActivity"
      ;;
    "google-play-store")
      package_name="com.android.vending"
      launcher_activity="com.android.vending.AssetBrowserActivity"
      ;;
    "zar")
      package_name="ru.zdevs.zarchiver"
      launcher_activity="ru.zdevs.zarchiver.ZArchiver"
      ;;
    "file-manager")
      package_name="com.mi.android.globalFileexplorer"
      launcher_activity="com.android.fileexplorer.FileExplorerTabActivity"
      ;;
    "galeri")
      package_name="com.miui.gallery"
      launcher_activity="com.miui.gallery.activity.HomePageActivity"
      ;;
    "setelan")
      package_name="com.android.settings"
      launcher_activity="com.android.settings.Settings"
      ;;
    "yt")
      package_name="org.schabi.newpipe"
      launcher_activity="org.schabi.newpipe.MainActivity"
      ;;
    *)
      echo "Not Found Shortcut: $apk_name"
      return 1
      ;;
  esac
  am start -n "$package_name/$launcher_activity"
}
